--- 
language: node_js
node_js: 
- 0.8
env:
  global:
    secure: |-
      edhK6qlvAL2d86lb5SludMjH1/3CWNGXxck4P25hnYblTr+AaGaY+VXHS1eyhoh0Q3tUz3fDuVSQxYxBwYIVisMR2IirJBB7MogokicV5TpsUOjmHRp+r8MpqcjqqnbH2N8D70gXNuu2cFEMNS9VnPLNpcI0DWPuSbQ8TpLNGw4=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm link
- npm install -g grunt-cli

# Saucelabs only allows two concurrent browsers, so we do two seperate grunt
# tasks, each with two of the browsers running
script:
- grunt install
- grunt
- grunt karma:sauce1
- grunt karma:sauce2

after_success: ./build/update-gh-pages.sh

